-- COLOCANDO O BD EM USO
USE SALA_DE_AULA;

-- INSERINDO DADOS
 INSERT INTO ALUNOS
(NOME, 	DATA_NASCIMENTO, 	IDADE, 	E_MAIL, 
FONE_RES, 	FONE_COM, 	FAX, 	CELULAR,
PROFISSAO, 	EMPRESA )
VALUES
('CARLOS MAGNO', 	'1959.11.12', 	53,	 'magno@magno.com',
'23456789',	'23459876',	'', 	'998765432',
'ANALISTA DE SISTEMAS', 'IMPACTA TECNOLOGIA');

-- Consultar os dados inseridos na tabela
SELECT * FROM ALUNOS;

-- INSERINDO UM ÚNICO REGISTRO
 INSERT INTO ALUNOS
(NOME, 	DATA_NASCIMENTO, 	IDADE, 	E_MAIL, 
FONE_RES, 	FONE_COM, 	FAX, 	CELULAR,
PROFISSAO, 	EMPRESA )
VALUES
('GUSTAVO FERREIRA', 	'1987.04.27', 	28,	 'gustavo@gferreira.com',
'23456789',	'23459876',	'', 	'998765432',
'PROFESSOR', 'IMPACTA TECNOLOGIA');

-- Consultar os dados inseridos na tabela
SELECT * FROM ALUNOS;

-- INSERINDO MAIS DE UM REGISTRO
 INSERT INTO ALUNOS
(NOME, 	DATA_NASCIMENTO)
VALUES
('GUSTAVO', 	'1991-11-20'), 
('MARCOS', 	'1992-03-27'), 
('GABRIELA',	'1994-02-05'), 
('MARIA', 	'1999-08-05');

-- Consultar os dados inseridos na tabela
SELECT * FROM ALUNOS;

-- INSERINDO INFORMANDO AS COLUNAS – INSERT DECLARATIVO
 INSERT INTO ALUNOS
(NOME, 	DATA_NASCIMENTO, 	PROFISSAO)
VALUES
('JOÃO', 	'2000-1-1',		'ESTUDANTE')

-- INSERT DECLARATIVO + DE UM REGISTRO
 INSERT INTO ALUNOS
(NOME, 	DATA_NASCIMENTO, 	PROFISSAO)
VALUES
('MARCOS', 	 '1992-03-27',	'GERENTE'), 
('GABRIELA', '1994-02-05',	'ANALISTA'),

-- Consultar os dados inseridos na tabela
SELECT * FROM ALUNOS;

-- INSERINDO DE ACORDO COM A ESTRUTURA DA TABELA– INSERT POSICIONAL
INSERT INTO ALUNOS
VALUES
(‘André da Silva’, ‘1980.1.2’, 33, ‘andre@silva.com’,
‘23456789’,’23459876’,’’, ‘998765432’,
‘ANALISTA DE SISTEMAS’, ‘SOMA INFORMÁTICA’),
(‘Marcelo Soares’, ‘1983.4.21’, 30, ‘marcelo@soares.com’,
‘23456789’,’23459876’,’’, ‘998765432’,
‘INSTRUTOR’, ‘IMPACTA TECNOLOGIA’);

-- Consultar os dados inseridos na tabela
SELECT * FROM ALUNOS;

-- CRIANDO TABELA 
CREATE TABLE ALUNOS2
( NUM_ALUNO INT,	NOME VARCHAR(30),	DATA_NASCIMENTO DATETIME,	IDADE TINYINT,
E_MAIL VARCHAR(50),	FONE_RES CHAR(8),	FONE_COM CHAR(8),	FAX CHAR(8), CELULAR CHAR(9),
PROFISSAO VARCHAR(40), EMPRESA VARCHAR(50) );

-- INSERINDO COM SELECT
INSERT INTO ALUNOS2
SELECT * FROM ALUNOS;

-- VERIFICANDO TABELA 2
SELECT * FROM ALUNOS2;

-- Criando tabela com select
SELECT * 
INTO ALUNOS3
FROM ALUNOS;

-- VERIFICANDO TABELA 3
SELECT * FROM ALUNOS3;


 
